# Generated by Django 4.2.7 on 2024-01-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_publication_year_book_publicationyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titles',
        ),
    ]
