# Generated by Django 4.2.7 on 2024-01-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_title_book_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titles',
            new_name='title',
        ),
    ]
