# Generated by Django 4.2.7 on 2024-01-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_archiveloan_bookcopy_borrowedbook_reservedbook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
            ],
        ),
    ]
