# Generated by Django 4.2.7 on 2024-01-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='app.isbn'),
        ),
    ]
