# Generated by Django 4.2.7 on 2024-02-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_isbn_book_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
