# Generated by Django 4.2.7 on 2024-02-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_image_alter_isbn_isbn_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='availability',
        ),
    ]
